### ISSUE TITLE
Gutter marks drift as lines are added or removed

### ISSUE THREAD

**Issue by eddiesholl** [yacut/tester#18] opened 2017-05-30 07:13 UTC
This is an awesome little plugin. I've just started using it recently. I had noticed the gutter marks were accumulating, and I'm pretty sure what is happening is that as small edits are made to the test file, the old red and green marks are left instead of moved. I've added a screenshot showing what I'm talking about.

This is using tester-jest, I'm not sure if the change is needed here in the core code or down in the individual plugin.

![image](https://cloud.githubusercontent.com/assets/3746494/26571913/48c499de-455b-11e7-8fc4-83926189076f.png)

**Comment by yacut** [comment] 2017-05-30 07:16
Hello.

The issue is fixed in v1.2.1 with #17.

Please update the package.

**Closed as completed** 2017-06-12 06:34 UTC
Labels: bug
